---
# tasks file for apache

- name: Inclui task debian.yaml
  include: debian.yaml
  when: (ansible_facts['os_family'] == "Debian")

- name: Inclui task redhat.yaml
  include: redhat.yaml
  when: (ansible_facts['os_family'] == "RedHat")

- name: Criando diretório que irá hospedar os arquivos do site
  file:
    path: "{{ site_folder }}"
    state: directory
    mode: '0755'

- name: Copia arquivo index.html simples
  copy:
    src: index.html
    dest: "{{ site_folder }}"