---
# tasks file to install apache on redhat

- name: 'Instalando o Apache em distros derivadas do RedHat'
  yum:
    name: 
      - httpd
      - openssl
    state: latest
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - enableHttpd

- name: 'Criando diretório virtual host - RedHat'
  file:
    path: "/etc/httpd/vhost.d"    
    state: directory
  when: (ansible_facts['os_family'] == "RedHat")
  
- name: 'Criando virtual host com as configurações do site - RedHat'
  template:
    src: templates/site.conf
    dest: /etc/httpd/vhost.d/{{ log_prefix }}.conf
  when: (ansible_facts['os_family'] == "RedHat")
  notify:
    - addInHostsFile
    - addInHttpdFile
    - RestartHttpd
    - InstallWordPress
    - SetPermissionWP-CentOS